### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by aaronpk** [tantek/cassis#14]
I've started working on a PHP test suite in my fork. Right now I'm most interested in tests for the `ellipsize_to_word` function.

https://github.com/aaronpk/cassis/blob/master/tests/EllipsizeTest.php

It would be great if you could dump some notes in a comment here on test cases you use for this function. Even just some examples of original+truncated version for what you expect the function to do in all the edge cases would be useful. Thanks!

**Comment by tantek** [comment]
Hey is this done now with your pull request #23 and #24?

**Comment by aaronpk** [comment]
So it is!
