### ISSUE TITLE
Parse error with PHP 8

### ISSUE THREAD

**Issue by gRegorLove** [tantek/cassis#37]
Running PHP 8.0.2 this error occurs after including the `vendor/autoload.php`:

`Parse error: syntax error, unexpected token ";", expecting "{" in [truncated]/vendor/tantek/cassis/cassis.php on line 12`

It appears to be a syntax issue with the `$s.match` in `return $s.match(new RegExp(trim_slashes($p), "i"));`

Edit: might be due to the `match` control structure added in PHP 8.0.0: https://www.php.net/manual/en/control-structures.match.php

**Comment by gRegorLove** [comment]
I'm taking another look at this. From [shortly after](https://chat.indieweb.org/dev/2022-10-27#t1666829194999700) this issue in the chat logs, looks like we need to automate running post-process.php in GitHub Actions for new releases.

**Comment by aaronpk** [comment]
This has been solved in the source, let's track auto-building the php version in a separate issue: #44
