### ISSUE TITLE
Composer Compatibility

### ISSUE THREAD

**Issue by barnabywalters** [tantek/cassis#6]
It should be extremely easy to add composer compliance so PHP applications can install cassis and keep up with updates without bothering with git submodules.

Adding the following as `composer.json` then registering the package at packagist (which I can do if you don't want to make a new account) should work:

```javascript
{
    "name": "tantek/cassis", // or alternatively cassis/cassis
    "autoload": {
        "files": ["cassis.js"]
    }
}
```

**Comment by aaronpk** [comment]
This is available on packagist.org now https://packagist.org/packages/tantek/cassis
